#!/bin/bash

if (sleep 3); then
	ulimit -c unlimited
	xsetroot -solid "#005577"
	wmname LG3D

	footpedal

	dunst &
	barrier &
	compton &
	1password &
	slack &

	sleep 1 # wait for compton to start
	if [ -f ~/.wallpaper.png ]; then
		hsetroot -tile ~/.wallpaper.png
	else
		hsetroot -solid "#005577" 
	fi

fi &>> /tmp/dwm-startup.log &

while true; do 
	sleep 1
	xsetroot -name "$(dwm_status)"
done &

#xrandr --output DP-2 --scale 1x1 --mode 3840x2160 --fb 7680x2016 --pos 0x0         
#xrandr --output DP-0 --scale 1x1 --mode 3840x2160 --pos 3840x0


while true; do
  dwm 2>&1 >> /tmp/dwm.log
done

